/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `npm run schema2ts` to regenerate this file.
 */

/**
 * Image Source
 */
export type ImageSource = string;
/**
 * Image Sourceset
 */
export type ImageSourceset = string;
/**
 * Alt text
 */
export type AltText = string;
/**
 * Width
 */
export type Width = number;
/**
 * height
 */
export type Height = number;
/**
 * Image Class
 */
export type Class = string;
/**
 * ID
 */
export type ID = string;
/**
 * Itemprop
 */
export type Itemprop = string;
/**
 * Object fit
 */
export type ObjectFit = 'contain' | 'cover' | 'fill' | 'none' | 'scale-down';
/**
 * Render noscript fallback
 */
export type RenderNoscriptFallback = boolean;
/**
 * Load Image Lazily
 */
export type Lazy = boolean;
/**
 * Additional sources. This will result in a `picture`-Element
 */
export type Sources = {
  srcSet?: string;
  media?: string;
  type?: string;
  [k: string]: unknown;
}[];
export type PictureClass = string;

/**
 * Picture
 */
export interface PictureProps {
  src?: ImageSource;
  srcSet?: ImageSourceset;
  alt?: AltText;
  width?: Width;
  height?: Height;
  className?: Class;
  id?: ID;
  itemProp?: Itemprop;
  style?: Style;
  objectFit?: ObjectFit;
  noscript?: RenderNoscriptFallback;
  lazy?: Lazy;
  sources?: Sources;
  pictureClassName?: PictureClass;
  [k: string]: unknown;
}
/**
 * Style
 */
export interface Style {
  [k: string]: unknown;
}
