/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `npm run schema2ts` to regenerate this file.
 */

/**
 * Image source for news item
 */
export type Image = string;
/**
 * Date for news item
 */
export type Date = string;
/**
 * Link for news item
 */
export type Link = string;
/**
 * Title for news item
 */
export type Title = string;
/**
 * Bodytext for news item
 */
export type Bodytext = string;
export type Label = string;
export type Size = 's' | 'm' | 'l';
export type LinkTarget = string;
export type Removable = boolean;
export type Categories = TagLabel[];
export type UniqueId = number;

/**
 * News list collection of news items
 */
export interface NewsListProps {
  newsItems?: NewsListItem[];
  [k: string]: unknown;
}
/**
 * News list item
 */
export interface NewsListItem {
  image?: Image;
  date?: Date;
  link: Link;
  title?: Title;
  body?: Bodytext;
  categories?: Categories;
  index: UniqueId;
  [k: string]: unknown;
}
/**
 * Tag Label
 */
export interface TagLabel {
  label: Label;
  size?: Size;
  link?: LinkTarget;
  removable?: Removable;
  [k: string]: unknown;
}
