/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `yarn run schema` to regenerate this file.
 */

/**
 * Select an image to display inside the quote, to the left
 */
export type ImageSource = string;
/**
 * Copy text for the element
 */
export type TextContent = string;
/**
 * Optionally display the source for the quote
 */
export type Source = string;
/**
 * Optionally display a byline for the quote's source
 */
export type SourceAddition = string;
/**
 * Additional css classes attached to the wrapping element
 */
export type Class = string;
/**
 * Optional custom component identifier
 */
export type KsComponentAttribute = string;

/**
 * Component to display a rich quote
 */
export interface QuoteProps {
  image?: ImageSource;
  text: TextContent;
  source?: Source;
  byline?: SourceAddition;
  className?: Class;
  component?: KsComponentAttribute;
  [k: string]: unknown;
}
