/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `npm run schema2ts` to regenerate this file.
 */

/**
 * Picture source
 */
export type Source = string;
/**
 * Alt text to display for picture
 */
export type AltText = string;
/**
 * Width of the picture
 */
export type Width = number;
/**
 * Height of the picture
 */
export type Height = number;
export type Logos = LogoImage[];

/**
 * Component to list logos or seals
 */
export interface LogoTilesProps {
  logos?: Logos;
  [k: string]: unknown;
}
export interface LogoImage {
  src?: Source;
  alt?: AltText;
  width?: Width;
  height?: Height;
  [k: string]: unknown;
}
