/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `yarn run schema` to regenerate this file.
 */

import type { ContactProps } from '@kickstartds/base/lib/contact/typing';
import type { PostMetaProps } from '@kickstartds/blog/lib/post-meta/typing';
import type { PostShareBarProps } from '@kickstartds/blog/lib/post-share-bar/typing';

export type Author = ContactProps & {
  headline?: {
    [k: string]: unknown;
  } & Text;
};
/**
 * Text content for the headline
 */
export type Text = string;
/**
 * Additional css classes attached to the wrapping element
 */
export type Class = string;
/**
 * Optional custom component identifier
 */
export type KsComponentAttribute = string;

/**
 * Post Aside
 */
export interface PostAsideProps {
  author?: Author;
  /**
   * Referenced component PostMetaProps
   */
  meta?: PostMetaProps;
  /**
   * Referenced component PostShareBarProps
   */
  shareBar?: PostShareBarProps;
  className?: Class;
  component?: KsComponentAttribute;
}
