/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `npm run schema2ts` to regenerate this file.
 */

/**
 * The label for the element
 */
export type Label = string;
/**
 * The name of the input element, used when submitting an HTML form
 */
export type Name = string;

/**
 * A Radio Group allows users to select one item from a list of choices.
 */
export interface RadioGroupProps {
  label: Label;
  name?: Name;
  [k: string]: unknown;
}
