version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
    open-pull-requests-limit: 15
    versioning-strategy: increase
    reviewers:
      - lmestel
      - julrich
