/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `npm run schema2ts` to regenerate this file.
 */

/**
 * The label for the element
 */
export type Label = string;
/**
 * The value of the input element, used when submitting an HTML form
 */
export type Value = string;
/**
 * The name of the input element, used when submitting an HTML form
 */
export type Name = string;
/**
 * Whether the input is disabled
 */
export type Disabled = boolean;
/**
 * Whether the element should be selected
 */
export type Selected = boolean;
/**
 * Whether the input is disabled
 */
export type Disabled1 = boolean;
export type Options = {
  value?: string;
  label: string;
  selected?: Selected;
  disabled?: Disabled1;
  [k: string]: unknown;
}[];

/**
 * Input that allow users to select a single option from a list of mutually exclusive options.
 */
export interface SelectFieldProps {
  label?: Label;
  value?: Value;
  name?: Name;
  disabled?: Disabled;
  options?: Options;
  [k: string]: unknown;
}
