/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `yarn run schema` to regenerate this file.
 */

/**
 * The label for the element
 */
export type Label = string;
/**
 * The name of the input element, used when submitting an HTML form
 */
export type Name = string;
/**
 * Wheter the input is invalid
 */
export type Invalid = boolean;
/**
 * Message to show if the input is invalid
 */
export type InvalidMessage = string;
/**
 * Whether the input is disabled
 */
export type Disabled = boolean;
/**
 * Help text that gives more context about what a user needs to input
 */
export type HintMessage = string;
export type Options = RadioButton[];
/**
 * Additional css classes attached to the wrapping element
 */
export type Class = string;
/**
 * Optional custom component identifier
 */
export type KsComponentAttribute = string;

/**
 * A Radio Group allows users to select one item from a list of choices.
 */
export interface RadioGroupProps {
  label: Label;
  name?: Name;
  invalid?: Invalid;
  invalidMessage?: InvalidMessage;
  options?: Options;
  className?: Class;
  component?: KsComponentAttribute;
}
/**
 * Radio buttons allow users to select a single option from a list of mutually exclusive options.
 */
export interface RadioButton {
  label: Label;
  disabled?: Disabled;
  hint?: HintMessage;
}
