/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import type { InputProps } from '@kickstartds/form/lib/input/typing';

export type Options = RadioButton[];
/**
 * Additional css classes attached to the wrapping element
 */
export type Class = string;
/**
 * Optional custom component identifier
 */
export type KsComponentAttribute = string;

/**
 * A Radio Group allows users to select one item from a list of choices.
 */
export interface RadioGroupProps {
  /**
   * Referenced component InputProps
   */
  label: InputProps;
  /**
   * Referenced component InputProps
   */
  name?: InputProps;
  /**
   * Referenced component InputProps
   */
  invalid?: InputProps;
  /**
   * Referenced component InputProps
   */
  invalidMessage?: InputProps;
  options?: Options;
  className?: Class;
  component?: KsComponentAttribute;
}
/**
 * Radio buttons allow users to select a single option from a list of mutually exclusive options.
 */
export interface RadioButton {
  /**
   * Referenced component InputProps
   */
  label: InputProps;
  /**
   * Referenced component InputProps
   */
  disabled?: InputProps;
  /**
   * Referenced component InputProps
   */
  hint?: InputProps;
  [k: string]: unknown;
}
