/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `yarn run schema` to regenerate this file.
 */

import type { InputProps } from '@kickstartds/form/lib/input/typing';

export type Options = Checkbox[];
/**
 * Additional css classes attached to the wrapping element
 */
export type Class = string;
/**
 * Optional custom component identifier
 */
export type KsComponentAttribute = string;

/**
 * A CheckboxGroup allows users to select one or more items from a list of choices.
 */
export interface CheckboxGroupProps {
  /**
   * Referenced component InputProps
   */
  label: InputProps;
  /**
   * Referenced component InputProps
   */
  name?: InputProps;
  /**
   * Referenced component InputProps
   */
  invalid?: InputProps;
  /**
   * Referenced component InputProps
   */
  invalidMessage?: InputProps;
  options?: Options;
  className?: Class;
  component?: KsComponentAttribute;
}
/**
 * Checkboxes allow users to select multiple items from a list of individual items, or to mark one individual item as selected.
 */
export interface Checkbox {
  /**
   * Referenced component InputProps
   */
  label: InputProps;
  /**
   * Referenced component InputProps
   */
  disabled?: InputProps;
  /**
   * Referenced component InputProps
   */
  hint?: InputProps;
  [k: string]: unknown;
}
