/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `npm run schema2ts` to regenerate this file.
 */

/**
 * Picture source
 */
export type Source = string;
/**
 * Alt text to display for picture
 */
export type AltText = string;
/**
 * Width of the picture
 */
export type Width = number;
/**
 * Height of the picture
 */
export type Height = number;
/**
 * Name, company name, etc.
 */
export type Title = string;
/**
 * Position, profession, department, location, etc.
 */
export type Subtitle = string;
export type PhoneNumber = string;
export type EmailAddress = string;
export type CopyText = string;

/**
 * Component to show contact information
 */
export interface ContactProps {
  image?: Image;
  title?: Title;
  subtitle?: Subtitle;
  phone?: PhoneNumber;
  email?: EmailAddress;
  copy?: CopyText;
  [k: string]: unknown;
}
export interface Image {
  src?: Source;
  alt?: AltText;
  width?: Width;
  height?: Height;
  [k: string]: unknown;
}
