/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `npm run schema2ts` to regenerate this file.
 */

/**
 * Main Headline portion of Headline
 */
export type MainHeadline = string;
/**
 * Sub Headline portion of Headline
 */
export type SubHeadline = string;
/**
 * Image for Textpic
 */
export type Image = string;
/**
 * Caption for Textpic
 */
export type Caption = string;
/**
 * Bodytext
 */
export type Content = string;

/**
 * Textpic Intextleft element
 */
export interface TextpicIntextleftProps {
  headline: Headline;
  textpic: Textpic;
  content: Content;
  [k: string]: unknown;
}
/**
 * Headline for Textpic element
 */
export interface Headline {
  mainheader: MainHeadline;
  subheader: SubHeadline;
  [k: string]: unknown;
}
/**
 * Textpic for Textpic element
 */
export interface Textpic {
  image: Image;
  caption: Caption;
  [k: string]: unknown;
}
