/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `yarn run schema` to regenerate this file.
 */

export type Caption = string;
/**
 * First colum is head
 */
export type ColumnHead = boolean;
/**
 * First row is head
 */
export type RowHead = boolean;
export type TableRows = string[][];
/**
 * Stack table on small screens
 */
export type Responsive = boolean;
export type TableVariant = 'border' | 'zebra';
/**
 * Add additional css classes that should be applied to the table
 */
export type AdditionalClasses = string;
/**
 * Optional custom component identifier
 */
export type KsComponentAttribute = string;

/**
 * Table
 */
export interface TableProps {
  caption?: Caption;
  colHead?: ColumnHead;
  rowHead?: RowHead;
  rows?: TableRows;
  responsive?: Responsive;
  variant?: TableVariant;
  className?: AdditionalClasses;
  component?: KsComponentAttribute;
  [k: string]: unknown;
}
