/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `yarn run schema` to regenerate this file.
 */

/**
 * A short title of the notification
 */
export type Title = string;
/**
 * The main message delivered by the notification
 */
export type Message = string;
/**
 * Choose the type of information being displayed in the notification
 */
export type Type = 'plain' | 'info' | 'warning' | 'succes' | 'error' | 'user';
/**
 * Choose whether the element is closable or not
 */
export type Close = boolean;
/**
 * Choose whether the action can be undone or not
 */
export type Undo = boolean;
/**
 * Choose whether the action can be undone or not
 */
export type Reply = boolean;
/**
 * Add additional css classes that should be applied to the label
 */
export type AdditionalClasses = string;
/**
 * Optional custom component identifier
 */
export type KsComponentAttribute = string;

/**
 * Component to render a pill / tag / label
 */
export interface NotificationProps {
  title?: Title;
  message?: Message;
  type?: Type;
  actions?: {
    close?: Close;
    undo?: Undo;
    accept?: Reply;
    [k: string]: unknown;
  };
  className?: AdditionalClasses;
  component?: KsComponentAttribute;
}
