/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `yarn run schema` to regenerate this file.
 */

import type { ButtonProps } from '@kickstartds/base/lib/button/typing';
import type { TagLabelProps } from '@kickstartds/base/lib/tag-label/typing';
import type { ContactProps } from '@kickstartds/base/lib/contact/typing';
import type { CollapsibleBoxProps } from '@kickstartds/base/lib/collapsible-box/typing';
import type { ContentBoxProps } from '@kickstartds/base/lib/content-box/typing';
import type { HeadlineProps } from '@kickstartds/base/lib/headline/typing';
import type { TextMediaProps } from '@kickstartds/base/lib/text-media/typing';
import type { TeaserBoxProps } from '@kickstartds/base/lib/teaser-box/typing';
import type { TeaserRowProps } from '@kickstartds/base/lib/teaser-row/typing';

/**
 * Width of section to use
 */
export type Width = 'narrow' | 'default' | 'wide' | 'max' | 'full';
/**
 * Width of headline to use
 */
export type HeadlineWidth = 'unset' | 'narrow' | 'default' | 'wide';
/**
 * Choose an alignment for the headline
 */
export type HeadlineAlignment = 'left' | 'center' | 'right';
/**
 * Width of content to use
 */
export type ContentWidth = 'unset' | 'narrow' | 'default' | 'wide';
/**
 * Choose an alignment for the content
 */
export type ContentAlignment = 'left' | 'center' | 'right';
/**
 * Size of gutter to use
 */
export type Gutter = 'large' | 'default' | 'small' | 'none';
/**
 * Layout mode used for section contents
 */
export type Mode = 'default' | 'tile' | 'list';
/**
 * Allowed content for the section
 */
export type Content = (
  | ButtonProps
  | TagLabelProps
  | ContactProps
  | CollapsibleBoxProps
  | ContentBoxProps
  | HeadlineProps
  | TextMediaProps
  | TeaserBoxProps
  | TeaserRowProps
)[];
/**
 * Type of background
 */
export type Background = 'default' | 'accent' | 'bold';
/**
 * Whether to invert the section
 */
export type Inverted = boolean;
/**
 * Amount of spacing before the section
 */
export type SpaceBefore = 'default' | 'small' | 'none';
/**
 * Amount of spacing after the section
 */
export type SpaceAfter = 'default' | 'small' | 'none';
/**
 * Select the headline level to use, or p alternatively
 */
export type Level = 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'p';
/**
 * Select the headline style to use
 */
export type Style = 'none' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'p';
/**
 * Choose an alignment for the headline
 */
export type Alignment = 'left' | 'center' | 'right';
/**
 * Text content for the headline
 */
export type Text = string;
/**
 * Text content for the optional subheadline
 */
export type Subheadline = string;
/**
 * Add additional spacing to the bottom of the headline
 */
export type BottomSpacing = 'minimum' | 'small' | 'large';
/**
 * Add additional css classes that should be applied to the headline
 */
export type AdditionalClasses = string;
/**
 * Optional custom component identifier
 */
export type KsComponentAttribute = string;
/**
 * Add additional css classes that should be applied to the section
 */
export type AdditionalClass = string;
/**
 * Optional custom component identifier
 */
export type KsComponentAttribute1 = string;

export interface SectionProps {
  width?: Width;
  headlineWidth?: HeadlineWidth;
  headlineAlign?: HeadlineAlignment;
  contentWidth?: ContentWidth;
  contentAlign?: ContentAlignment;
  gutter?: Gutter;
  mode?: Mode;
  content?: Content;
  background?: Background;
  inverted?: Inverted;
  spaceBefore?: SpaceBefore;
  spaceAfter?: SpaceAfter;
  headline?: Headline;
  className?: AdditionalClass;
  component?: KsComponentAttribute1;
}
/**
 * Headline
 */
export interface Headline {
  level?: Level;
  styleAs?: Style;
  align?: Alignment;
  content: Text;
  subheadline?: Subheadline;
  spaceAfter?: BottomSpacing;
  className?: AdditionalClasses;
  component?: KsComponentAttribute;
}
