# Work in progress!!

version: 2.1

defaults: &defaults
  docker:
    - image: circleci/node:12
  working_directory: /mnt/ramdisk
  resource_class: medium+

aliases:
  - &restore-cache
    keys:
      - yarn config set cache-folder /mnt/ramdisk/.yarn-cache
      - yarn-{{ checksum "yarn.lock" }}-{{ checksum ".circleci/config.yml" }}
      - yarn-{{ checksum "yarn.lock" }}
      - yarn-
  - &save-cache
    key: yarn-{{ checksum "yarn.lock" }}-{{ checksum ".circleci/config.yml" }}
    paths:
      - .yarn-cache
      - node_modules
  - &attach_workspace
    attach_workspace:
      at: /mnt/ramdisk

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-cache
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile --cache-folder ~/.cache/yarn
      - save_cache: *save-cache
      - run:
          name: Build
          environment:
            NODE_ENV: production
          command: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - packages/components

  chromatic:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-cache
      - *attach_workspace
      - run:
          name: Build Storybook & deploy to Chromatic
          command: yarn run chromatic

  release:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-cache
      - *attach_workspace
      - run:
          name: Create Release
          command: yarn auto shipit --dry-run

  publish-base:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-cache
      - *attach_workspace
      - run:
          name: Publish Chromatic Module Base
          command: CHROMATIC_PROJECT_TOKEN=${CHROMATIC_PROJECT_TOKEN_BASE} yarn run chromatic-base

  publish-blog:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-cache
      - *attach_workspace
      - run:
          name: Publish Chromatic Module Blog
          command: CHROMATIC_PROJECT_TOKEN=${CHROMATIC_PROJECT_TOKEN_BLOG} yarn run chromatic-blog

  publish-content:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-cache
      - *attach_workspace
      - run:
          name: Publish Chromatic Module Content
          command: CHROMATIC_PROJECT_TOKEN=${CHROMATIC_PROJECT_TOKEN_CONTENT} yarn run chromatic-content

  publish-form:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-cache
      - *attach_workspace
      - run:
          name: Publish Chromatic Module Form
          command: CHROMATIC_PROJECT_TOKEN=${CHROMATIC_PROJECT_TOKEN_FORM} yarn run chromatic-form

workflows:
  release:
    jobs:
      - build

      - chromatic:
          context: kickstartDS
          requires:
            - build

      - release:
          context: kickstartDS
          requires:
            - build

      - publish-base:
          context: kickstartDS
          requires:
            - build

      - publish-blog:
          context: kickstartDS
          requires:
            - build

      - publish-content:
          context: kickstartDS
          requires:
            - build

      - publish-form:
          context: kickstartDS
          requires:
            - build
