# Work in progress!!

version: 2.1

defaults: &defaults
  docker:
    - image: circleci/node:12
  working_directory: ~/repo

aliases:
  - &restore-cache
    keys:
      - yarn-{{ checksum "yarn.lock" }}-{{ checksum ".circleci/config.yml" }}
      - yarn-{{ checksum "yarn.lock" }}
      - yarn-
  - &save-cache
    key: yarn-{{ checksum "yarn.lock" }}-{{ checksum ".circleci/config.yml" }}
    paths:
      - ~/.cache/yarn
      - node_modules
  - &attach_workspace
    attach_workspace:
      at: ~/repo

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-cache
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile --cache-folder ~/.cache/yarn
      - save_cache: *save-cache
      - run:
          name: Build
          environment:
            NODE_ENV: production
          command: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - packages/components

  chromatic:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-cache
      - *attach_workspace
      - run:
          name: Build Storybook & deploy to Chromatic
          command: yarn run chromatic

  release:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-cache
      - *attach_workspace
      - run:
          name: Create Release
          command: yarn auto shipit --dry-run

  publish:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-cache
      - *attach_workspace
      - run:
          name: Publish Chromatic Module Base
          command: CHROMATIC_PROJECT_TOKEN=${CHROMATIC_PROJECT_TOKEN_BASE} yarn run chromatic-base
      - run:
          name: Publish Chromatic Module Blog
          command: CHROMATIC_PROJECT_TOKEN=${CHROMATIC_PROJECT_TOKEN_BLOG} yarn run chromatic-blog
      - run:
          name: Publish Chromatic Module Content
          command: CHROMATIC_PROJECT_TOKEN=${CHROMATIC_PROJECT_TOKEN_CONTENT} yarn run chromatic-content
      - run:
          name: Publish Chromatic Module Form
          command: CHROMATIC_PROJECT_TOKEN=${CHROMATIC_PROJECT_TOKEN_FORM} yarn run chromatic-form

workflows:
  release:
    jobs:
      - build

      - chromatic:
          context: kickstartDS
          requires:
            - build

      - release:
          context: kickstartDS
          requires:
            - build

      - publish:
          context: kickstartDS
          requires:
            - build
