# Work in progress!!

version: 2.1

defaults: &defaults
  docker:
    - image: circleci/node:12
  working_directory: ~/repo

aliases:
  - &restore-cache
    keys:
      - yarn-{{ checksum "yarn.lock" }}-{{ checksum ".circleci/config.yml" }}
      - yarn-{{ checksum "yarn.lock" }}
      - yarn-
  - &save-cache
    key: yarn-{{ checksum "yarn.lock" }}-{{ checksum ".circleci/config.yml" }}
    paths:
      - ~/.cache/yarn
      - node_modules
  - &attach_workspace
      attach_workspace:
        at: ~/repo

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-cache
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile --cache-folder ~/.cache/yarn
      - save_cache: *save-cache
      - run:
          name: Build
          environment:
            NODE_ENV: production
          command: yarn build
      - run:
          command: rm -rf .git
      - persist_to_workspace:
          root: .
          paths:
            - .

  chromatic:
    <<: *defaults
    steps:
      - *attach_workspace
      - run:
          name: Build Storybook & deploy to Chromatic
          command: yarn run chromatic

  release:
    <<: *defaults
    steps:
      - *attach_workspace
      - run:
          name: Create Release
          command: yarn auto shipit --dry-run

workflows:
  release:
    jobs:
      - build

      - chromatic:
          context: kickstartDS
          requires:
            - build

      - release:
          context: kickstartDS
          requires:
            - build

