version: 2.1

defaults: &defaults
  docker:
    - image: cimg/node:16.14
  working_directory: /mnt/ramdisk
  resource_class: medium+

release_branches_only: &release_branches_only
  filters:
    branches:
      only:
        - master
        - next

aliases:
  - &save-cache-yarn
    key: yarn-{{ checksum "yarn.lock" }}-{{ checksum ".circleci/config.yml" }}
    paths:
      - .yarn-cache
  - &restore-cache-yarn
    keys:
      - yarn-{{ checksum "yarn.lock" }}-{{ checksum ".circleci/config.yml" }}
      - yarn-{{ checksum "yarn.lock" }}
  - &save-cache-node
    key: node-{{ checksum "yarn.lock" }}-{{ checksum ".circleci/config.yml" }}
    paths:
      - node_modules
  - &restore-cache-node
    keys:
      - node-{{ checksum "yarn.lock" }}-{{ checksum ".circleci/config.yml" }}
      - node-{{ checksum "yarn.lock" }}
      - node-
  - &attach_workspace
    attach_workspace:
      at: /mnt/ramdisk

jobs:
  release:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-cache-yarn
      - restore_cache: *restore-cache-node
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile --cache-folder /mnt/ramdisk/.yarn-cache
      - save_cache: *save-cache-yarn
      - save_cache: *save-cache-node
      - run:
          name: Build
          environment:
            NODE_ENV: production
          command: yarn build
      - run:
          name: Create Release
          environment:
            HUSKY: 0
          command: yarn auto shipit
      - persist_to_workspace:
          root: .
          paths:
            - packages/components
            - packages/tools/storybook/.storybook

  chromatic:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-cache-node
      - *attach_workspace
      - run:
          name: Build Storybook & deploy to Chromatic
          command: yarn run chromatic

  docusaurus:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-cache-node
      - *attach_workspace
      - run:
          name: Build docs
          command: yarn run docusaurus-build --out-dir=../../../docs
      - run:
          name: Compress docs folder
          command: tar -czf docs.tar.gz docs
      - store_artifacts:
          path: docs.tar.gz
      - run:
          name: Trigger website deployment
          command: |
            curl --request POST \
              --url "https://circleci.com/api/v2/project/gh/kickstartDS/website-deployment/pipeline" \
              --header "Circle-Token: ${CIRCLE_CI_WEBSITE_BUILD_TOKEN}" \
              --header "content-type: application/json" \
              --data '{"branch":"master","parameters":{"run_workflow_deploy":true, "website_branch":"master"}}'

  publish-base:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-cache-node
      - *attach_workspace
      - run:
          name: Publish Chromatic Module Base
          command: CHROMATIC_PROJECT_TOKEN=${CHROMATIC_PROJECT_TOKEN_BASE} yarn run chromatic-base

  publish-blog:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-cache-node
      - *attach_workspace
      - run:
          name: Publish Chromatic Module Blog
          command: CHROMATIC_PROJECT_TOKEN=${CHROMATIC_PROJECT_TOKEN_BLOG} yarn run chromatic-blog

  publish-form:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-cache-node
      - *attach_workspace
      - run:
          name: Publish Chromatic Module Form
          command: CHROMATIC_PROJECT_TOKEN=${CHROMATIC_PROJECT_TOKEN_FORM} yarn run chromatic-form

workflows:
  release:
    jobs:
      - release:
          context: kickstartDS
          filters:
            branches:
              ignore: /^dependabot\/.*$/

      - chromatic:
          context: kickstartDS
          requires:
            - release

      - docusaurus:
          filters:
            branches:
              only: feature/docs
          context: kickstartDS
          requires:
            - release

      - publish-base:
          <<: *release_branches_only
          context: kickstartDS
          requires:
            - release

      - publish-blog:
          <<: *release_branches_only
          context: kickstartDS
          requires:
            - release

      - publish-form:
          <<: *release_branches_only
          context: kickstartDS
          requires:
            - release
