/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `yarn run schema` to regenerate this file.
 */

/**
 * The label for the element
 */
export type Label = string;
/**
 * The value of the input element, used when submitting an HTML form
 */
export type Value = string;
/**
 * The name of the input element, used when submitting an HTML form
 */
export type Name = string;
/**
 * Whether the input is disabled
 */
export type Disabled = boolean;
/**
 * Temporary text that occupies the text input when it is empty
 */
export type Placeholder = string;
/**
 * Hints at the type of data that might be entered by the user while editing the element or its contents
 */
export type InputMode =
  | 'none'
  | 'text'
  | 'search'
  | 'url'
  | 'tel'
  | 'email'
  | 'numeric'
  | 'decimal';
export type Options = string[];
/**
 * Hide label visually
 */
export type HideLabel = boolean;
/**
 * Wheter the input is invalid
 */
export type Invalid = boolean;
/**
 * Message to show if the input is invalid
 */
export type InvalidMessage = string;
/**
 * Help text that gives more context about what a user needs to input
 */
export type HintMessage = string;
/**
 * Additional css classes attached to the select element
 */
export type Class = string;

/**
 * Input that allow users to select a single option from a list of mutually exclusive options.
 */
export interface ComboBoxProps {
  label?: Label;
  value?: Value;
  name?: Name;
  disabled?: Disabled;
  placeholder?: Placeholder;
  inputMode?: InputMode;
  options?: Options;
  hideLabel?: HideLabel;
  invalid?: Invalid;
  invalidMessage?: InvalidMessage;
  hint?: HintMessage;
  className?: Class;
  [k: string]: unknown;
}
