/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `yarn run schema` to regenerate this file.
 */

/**
 * Url (mp4) for the video to display
 */
export type Source = string;
/**
 * Use an iframe embed
 */
export type EmbeddedIframe = boolean;
/**
 * Title to use for the video
 */
export type VideoTitle = string;
/**
 * Width of the video
 */
export type Width = number;
/**
 * Height of the video
 */
export type Height = number;
/**
 * Display media item over full width
 */
export type FullWidthMedia = boolean;
/**
 * Caption
 */
export type Caption = string;

export interface MediaVideoProps {
  video?: Video;
  full?: FullWidthMedia;
  caption?: Caption;
}
/**
 * Video item to display
 */
export interface Video {
  src: Source;
  iframe?: EmbeddedIframe;
  title?: VideoTitle;
  width: Width;
  height: Height;
}
