/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `yarn run schema` to regenerate this file.
 */

import type { MediaVideoProps } from '@kickstartds/base/lib/media-video/typing';
import type { MediaImageProps } from '@kickstartds/base/lib/media-image/typing';
import type { MediaLazyimageProps } from '@kickstartds/base/lib/media-lazyimage/typing';

/**
 * Copy text for the element
 */
export type TextContent = string;
/**
 * In relation to the text content
 */
export type MediaAlignment =
  | 'above-left'
  | 'above-center'
  | 'above-right'
  | 'beside-left'
  | 'beside-right'
  | 'intext-left'
  | 'intext-right'
  | 'below-left'
  | 'below-center'
  | 'below-right';
/**
 * Collection of media items to display
 */
export type Media = (MediaVideoProps | MediaImageProps | MediaLazyimageProps)[];
/**
 * Additional css classes attached to the wrapping element
 */
export type Class = string;
/**
 * Optional custom component identifier
 */
export type KsComponentAttribute = string;

/**
 * Component to display copy text, including media
 */
export interface TextMediaProps {
  text: TextContent;
  mediaAlignment?: MediaAlignment;
  media?: Media;
  className?: Class;
  component?: KsComponentAttribute;
}
