/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `npm run schema2ts` to regenerate this file.
 */

/**
 * Product
 */
export interface ProductProps {
  productItems?: {
    slideComponent?: string;
    topic?: string;
    number?: string;
    content?: string;
    price?: string;
    link?: string;
    href?: string;
    card?: {
      cardImage?: string;
      special?: string;
      additionalContent?: boolean;
      [k: string]: unknown;
    };
    detail?: {
      detailImage?: string;
      [k: string]: unknown;
    };
    slider?: {
      sliderItemImage?: string;
      [k: string]: unknown;
    };
    teaser?: {
      clickable?: boolean;
      productTeaserLarge?: boolean;
      withoutSpacing?: boolean;
      fullWidth?: boolean;
      id?: string;
      teaserImage?: string;
      [k: string]: unknown;
    };
    imageSlider?: {
      slideComponent?: string;
      previewComponent?: string;
      thumbnail?: string;
      imageWidth?: string;
      imageHeight?: string;
      image?: string;
      [k: string]: unknown;
    };
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}
