/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `npm run schema2ts` to regenerate this file.
 */

/**
 * The label for the element
 */
export type Label = string;
/**
 * Whether the input is disabled
 */
export type Disabled = boolean;
/**
 * Wheter the input is invalid
 */
export type Invalid = boolean;
/**
 * Message to show if the input is invalid
 */
export type InvalidMessage = string;

/**
 * Checkboxes allow users to select multiple items from a list of individual items, or to mark one individual item as selected.
 */
export interface CheckboxProps {
  label: Label;
  disabled?: Disabled;
  invalid?: Invalid;
  invalidMessage?: InvalidMessage;
  [k: string]: unknown;
}
