/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `npm run schema2ts` to regenerate this file.
 */

/**
 * Headline Level
 */
export type HeadlineLevel = 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'p';
/**
 * Text Align
 */
export type TextAlign = 'left' | 'center' | 'right';
/**
 * Headline Text
 */
export type HeadlineText = string;
/**
 * Subheadline Text
 */
export type SubheadlineText = string;
/**
 * Bottom Spacing
 */
export type BottomSpacing = 'none' | 'small' | 'large';
/**
 * Page Header
 */
export type PageHeader = boolean;

/**
 * Headline
 */
export interface ContentHeadlineProps {
  level: HeadlineLevel;
  align?: TextAlign;
  content: HeadlineText;
  subheader?: SubheadlineText;
  spaceAfter?: BottomSpacing;
  pageHeader?: PageHeader;
  [k: string]: unknown;
}
