/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `npm run schema2ts` to regenerate this file.
 */

/**
 * collapsible box
 */
export interface CollapsibleBoxProps {
  'header-text'?: string;
  'collapsed-box'?: string;
  [k: string]: unknown;
}
