/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `yarn run schema` to regenerate this file.
 */

/**
 * Input id
 */
export type ID = string;
/**
 * Name
 */
export type Name = string;
/**
 * Toggle is checked
 */
export type Checked = boolean;
/**
 * Toggle is disabled
 */
export type Disabled = boolean;

/**
 * Toggle Switch
 */
export interface ToggleSwitchProps {
  id: ID;
  name: Name;
  checked: Checked;
  disabled: Disabled;
  [k: string]: unknown;
}
