/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `npm run schema2ts` to regenerate this file.
 */

/**
 * Quote
 */
export interface QuoteProps {
  image?: string;
  text: string;
  source?: string;
  date?: string;
  [k: string]: unknown;
}
