/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `yarn run schema` to regenerate this file.
 */

/**
 * News Detail Video
 */
export interface NewsDetailVideoProps {
  date?: string;
  [k: string]: unknown;
}
