/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `yarn run schema` to regenerate this file.
 */

import type { HeadlineProps } from '@kickstartds/base/lib/headline/typing';

/**
 * Text content for the headline
 */
export type Text = string;
/**
 * Add additional spacing to the bottom of the headline
 */
export type BottomSpacing = 'minimum' | 'small' | 'large';
/**
 * Open link in new Tab
 */
export type OpenLinkInNewTab = boolean;
/**
 * Additional css classes attached to the wrapping element
 */
export type Class = string;
/**
 * Optional custom component identifier
 */
export type KsComponentAttribute = string;

/**
 * Post Share Bar
 */
export interface PostShareBarProps {
  headline?: {
    content?: Text;
    spaceAfter?: string & BottomSpacing;
  } & HeadlineProps;
  links?: ShareLink[];
  className?: Class;
  component?: KsComponentAttribute;
}
export interface ShareLink {
  href?: string;
  icon?: string;
  title?: string;
  newTab?: OpenLinkInNewTab;
}
