// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  introSidebar: [{ type: 'autogenerated', dirName: 'intro' }],
  basicsSidebar: [{ type: 'autogenerated', dirName: 'basics' }],
  conceptsSidebar: [{ type: 'autogenerated', dirName: 'concepts' }],
  feedbackSidebar: [{ type: 'autogenerated', dirName: 'feedback' }],
  guidesSidebar: [{ type: 'autogenerated', dirName: 'guides' }],
  integrationSidebar: [{ type: 'autogenerated', dirName: 'integration' }],
  roadmapSidebar: [{ type: 'autogenerated', dirName: 'roadmap' }],
};

module.exports = sidebars;
