/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `npm run schema2ts` to regenerate this file.
 */

/**
 * Content-center for teaser box item
 */
export type ContentCenter = ContentCenter1 & ContentCenter2;
export type ContentCenter1 = boolean;
export type ContentCenter2 = string;
/**
 * Image for teaser box item
 */
export type Image = string;
/**
 * Title for teaser box item
 */
export type Title = string;
/**
 * Text for teaser box item
 */
export type Text = string;
/**
 * Image-spacing for teaser box item
 */
export type ImageSpacing = ImageSpacing1 & ImageSpacing2;
export type ImageSpacing1 = boolean;
export type ImageSpacing2 = string;
/**
 * Link Button Text for teaser box item
 */
export type LinkButtonText = string;
/**
 * Link target
 */
export type LinkTarget = string;
/**
 * Items for teaser box
 */
export type Items = Item[];

/**
 * Teaser Box element
 */
export interface TeaserBoxProps {
  items?: Items;
  [k: string]: unknown;
}
export interface Item {
  contentCenter: ContentCenter;
  image: Image;
  topic: Title;
  text: Text;
  imageSpacing?: ImageSpacing;
  linkButtonText: LinkButtonText;
  href: LinkTarget;
  [k: string]: unknown;
}
