/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `yarn run schema` to regenerate this file.
 */

import type { ButtonProps } from '@kickstartds/base/lib/button/typing';

/**
 * Headline for the teaser box. Displayed before the text, in bold
 */
export type Headline = string;
/**
 * Text for the teaser box
 */
export type TextContent = string;
export type Inverted = boolean;
/**
 * Hides the link. The box as a whole keeps being clickable
 */
export type HideLink = boolean;
/**
 * Additional css classes attached to the box
 */
export type Class = string;
/**
 * Optional custom component identifier
 */
export type KsComponentAttribute = string;

/**
 * Component to tease external content
 */
export interface TeaserProps {
  headline?: Headline;
  text?: TextContent;
  inverted?: Inverted;
  link?: ButtonProps & {
    hidden?: HideLink;
  };
  className?: Class;
  component?: KsComponentAttribute;
}
