/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `npm run schema2ts` to regenerate this file.
 */

/**
 * Image source for news item
 */
export type Image = string;
/**
 * Date for news item
 */
export type Date = string;
/**
 * Link for news item
 */
export type Link = string;
/**
 * Title for news item
 */
export type Title = string;
/**
 * Bodytext for news item
 */
export type Bodytext = string;
/**
 * Text to display inside tag label
 */
export type Label = string;
/**
 * Choose a size to scale the tag label up or down
 */
export type Size = 's' | 'm' | 'l';
/**
 * Set optional href to link the tag
 */
export type LinkTarget = string;
/**
 * Choose whether the element is removable or not
 */
export type Removable = boolean;
export type Categories = TagLabel[];
export type UniqueId = number;

/**
 * News latest collection of news items
 */
export interface NewsLatestProps {
  newsItems?: NewsLatestItem[];
  [k: string]: unknown;
}
/**
 * News latest item
 */
export interface NewsLatestItem {
  image?: Image;
  date?: Date;
  link: Link;
  title?: Title;
  body?: Bodytext;
  categories?: Categories;
  index: UniqueId;
  [k: string]: unknown;
}
/**
 * Component to render a pill / tag / label
 */
export interface TagLabel {
  label: Label;
  size: Size;
  link?: LinkTarget;
  removable?: Removable;
}
