/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Select an image to display inside the teaser box, at the top
 */
export type ImageSource = string;
/**
 * Choose the ratio used to crop and display the image
 */
export type ImageRatio = '4:3' | '16:9' | '1:1';
/**
 * Optionally add inner spacing to the displayed image
 */
export type ImageSpacing = boolean;

/**
 * Component to tease external content
 */
export interface TeaserBoxProps {
  image?: ImageSource;
  ratio: ImageRatio;
  imageSpacing?: ImageSpacing;
}
