/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `yarn run schema` to regenerate this file.
 */

import type { InputProps } from '@kickstartds/form/lib/input/typing';

/**
 * Additional css classes attached to the input element
 */
export type Class = string;
/**
 * Optional custom component identifier
 */
export type KsComponentAttribute = string;

/**
 * Checkboxes allow users to select multiple items from a list of individual items, or to mark one individual item as selected.
 */
export interface CheckboxProps {
  /**
   * Referenced component InputProps
   */
  label: InputProps;
  /**
   * Referenced component InputProps
   */
  disabled?: InputProps;
  /**
   * Referenced component InputProps
   */
  invalid?: InputProps;
  /**
   * Referenced component InputProps
   */
  invalidMessage?: InputProps;
  /**
   * Referenced component InputProps
   */
  hint?: InputProps;
  className?: Class;
  component?: KsComponentAttribute;
}
