/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `npm run schema2ts` to regenerate this file.
 */

/**
 * Choose a variant for the divider
 */
export type StyleOfTheDivider = 'default' | 'accent' | 'dark';

/**
 * Dividers bring clarity to a layout by grouping and dividing content in close proximity.
 */
export interface DividerProps {
  variant?: StyleOfTheDivider;
  [k: string]: unknown;
}
