/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import type { PictureProps } from '@kickstartds/base/lib/picture/typing';

/**
 * Additional css classes attached to the wrapping element
 */
export type Class = string;
/**
 * Optional custom component identifier
 */
export type KsComponentAttribute = string;

/**
 * Post Meta
 */
export interface PostMetaProps {
  author?: {
    name?: string;
    /**
     * Referenced component PictureProps
     */
    image?: PictureProps;
  };
  items?: MetaItem[];
  className?: Class;
  component?: KsComponentAttribute;
}
export interface MetaItem {
  icon?: string;
  text?: string;
}
