/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `yarn run schema` to regenerate this file.
 */

/**
 * The label for the element
 */
export type Label = string;
/**
 * The value of the input element, used when submitting an HTML form
 */
export type Value = string;
/**
 * The name of the input element, used when submitting an HTML form
 */
export type Name = string;
/**
 * Whether the input is disabled
 */
export type Disabled = boolean;
export type Options = {
  value?: string;
  label: string;
  disabled?: Disabled;
}[];
/**
 * Hide label visually
 */
export type HideLabel = boolean;
/**
 * Wheter the input is invalid
 */
export type Invalid = boolean;
/**
 * Message to show if the input is invalid
 */
export type InvalidMessage = string;
/**
 * Help text that gives more context about what a user needs to input
 */
export type HintMessage = string;
export type IconIdentifier = string;
/**
 * Additional css classes attached to the select element
 */
export type Class = string;
/**
 * Optional custom component identifier
 */
export type KsComponentAttribute = string;

/**
 * Input that allow users to select a single option from a list of mutually exclusive options.
 */
export interface SelectFieldProps {
  label?: Label;
  value?: Value;
  name?: Name;
  disabled?: Disabled;
  options?: Options;
  hideLabel?: HideLabel;
  invalid?: Invalid;
  invalidMessage?: InvalidMessage;
  hint?: HintMessage;
  icon?: IconIdentifier & string;
  className?: Class;
  component?: KsComponentAttribute;
}
