/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `yarn run schema` to regenerate this file.
 */

import type { InputProps } from '@kickstartds/form/lib/input/typing';

export type Options = {
  value?: string;
  label: string;
  /**
   * Referenced component InputProps
   */
  disabled?: InputProps;
}[];
export type IconIdentifier = string;
/**
 * Additional css classes attached to the select element
 */
export type Class = string;
/**
 * Optional custom component identifier
 */
export type KsComponentAttribute = string;

/**
 * Input that allow users to select a single option from a list of mutually exclusive options.
 */
export interface SelectFieldProps {
  /**
   * Referenced component InputProps
   */
  label?: InputProps;
  /**
   * Referenced component InputProps
   */
  value?: InputProps;
  /**
   * Referenced component InputProps
   */
  name?: InputProps;
  /**
   * Referenced component InputProps
   */
  disabled?: InputProps;
  options?: Options;
  /**
   * Referenced component InputProps
   */
  hideLabel?: InputProps;
  /**
   * Referenced component InputProps
   */
  invalid?: InputProps;
  /**
   * Referenced component InputProps
   */
  invalidMessage?: InputProps;
  /**
   * Referenced component InputProps
   */
  hint?: InputProps;
  icon?: IconIdentifier;
  className?: Class;
  component?: KsComponentAttribute;
}
