/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `yarn run schema` to regenerate this file.
 */

/**
 * Automatically move to next slide after 4 seconds without user interaction
 */
export type AutoPlay = boolean;
/**
 * Additional css classes attached to the wrapping element
 */
export type Class = string;
/**
 * Optional custom component identifier
 */
export type Component = string;
/**
 * Add arrows on the left and right to navigate to next or previous slide
 */
export type Arrows = 'none' | 'outer' | 'inner';

/**
 * Slider
 */
export interface SliderProps {
  autoplay?: AutoPlay;
  className?: Class;
  component?: Component;
  arrows?: Arrows;
  [k: string]: unknown;
}
