/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `npm run schema2ts` to regenerate this file.
 */

/**
 * Glossary
 */
export interface GlossaryProps {
  glossary?: {
    image?: {
      src?: string;
      caption?: string;
      positionX?: '' | 'left' | 'right';
      positionY?: 'top' | 'bottom';
      [k: string]: unknown;
    };
    content?: {
      headline?: string;
      id?: string;
      text?: string;
      content?: {
        headline?: string;
        id?: string;
        text?: string;
        [k: string]: unknown;
      }[];
      [k: string]: unknown;
    }[];
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
