/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `npm run schema2ts` to regenerate this file.
 */

export type Label = string;
export type Size = 's' | 'm' | 'l';
export type LinkTarget = string;
export type Removable = boolean;

/**
 * Tag Label
 */
export interface TagLabelProps {
  label: Label;
  size?: Size;
  link?: LinkTarget;
  removable?: Removable;
  [k: string]: unknown;
}
