/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `npm run schema2ts` to regenerate this file.
 */

/**
 * Business-card
 */
export interface BusinessCardBusinessCardProps {
  businessCard?: BusinessCard[];
  [k: string]: unknown;
}
/**
 * Business-card
 */
export interface BusinessCard {
  image?: string;
  logo?: string;
  address?: string;
  topic?: string;
  contactPersonImage?: string;
  phone?: string;
  email?: string;
  button1?: boolean;
  button2?: boolean;
  [k: string]: unknown;
}
