/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `yarn run schema` to regenerate this file.
 */

/**
 * Thumbnail Source
 */
export type ThumbnailSource = string;
/**
 * Lightbox Image Source
 */
export type LightboxImageSource = string;
/**
 * Width
 */
export type Width = number;
/**
 * height
 */
export type Height = number;
/**
 * Hover Zoom Icon
 */
export type HoverZoomIcon = boolean;
/**
 * Caption
 */
export type Caption = string;
/**
 * Hide caption visually
 */
export type HideCaptionVisually = boolean;
/**
 * Gallery identifier
 */
export type GalleryIdentifier = string;
/**
 * ID
 */
export type ID = string;
/**
 * Additional Image Class
 */
export type AdditionalImageClass = string;

/**
 * Lazy Lightbox Image
 */
export interface LazyLightboxImageProps {
  thumb?: ThumbnailSource;
  image?: LightboxImageSource;
  width?: Width;
  height?: Height;
  zoomIcon?: HoverZoomIcon;
  caption?: Caption;
  hideCaption?: HideCaptionVisually;
  gallery?: GalleryIdentifier;
  id?: ID;
  class?: AdditionalImageClass;
  [k: string]: unknown;
}
