/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Choose a variant for the divider
 */
export type StyleOfTheDivider = 'default' | 'accent';
/**
 * Add additional css classes that should be applied to the divider
 */
export type AdditionalClasses = string;
/**
 * Optional custom component identifier
 */
export type KsComponentAttribute = string;

/**
 * Dividers bring clarity to a layout by grouping and dividing content in close proximity.
 */
export interface DividerProps {
  variant?: StyleOfTheDivider;
  className?: AdditionalClasses;
  component?: KsComponentAttribute;
}
