/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `yarn run schema` to regenerate this file.
 */

import type { InputProps } from '@kickstartds/form/lib/input/typing';

/**
 * The type of input to render
 */
export type Type =
  | 'date'
  | 'datetime-local'
  | 'email'
  | 'month'
  | 'number'
  | 'password'
  | 'search'
  | 'tel'
  | 'text'
  | 'time'
  | 'url'
  | 'week';
/**
 * Hints at the type of data that might be entered by the user while editing the element or its contents
 */
export type InputMode =
  | 'none'
  | 'text'
  | 'search'
  | 'url'
  | 'tel'
  | 'email'
  | 'numeric'
  | 'decimal';
/**
 * Additional css classes attached to the input element
 */
export type Class = string;
/**
 * Optional custom component identifier
 */
export type KsComponentAttribute = string;

/**
 * TextFields are text inputs that allow users to input custom text entries with a keyboard.
 */
export interface TextFieldProps {
  /**
   * Referenced component InputProps
   */
  label?: InputProps;
  /**
   * Referenced component InputProps
   */
  value?: InputProps;
  /**
   * Referenced component InputProps
   */
  name?: InputProps;
  /**
   * Referenced component InputProps
   */
  disabled?: InputProps;
  /**
   * Referenced component InputProps
   */
  placeholder?: InputProps;
  type?: Type;
  inputMode?: InputMode;
  /**
   * Referenced component InputProps
   */
  hideLabel?: InputProps;
  /**
   * Referenced component InputProps
   */
  icon?: InputProps;
  /**
   * Referenced component InputProps
   */
  invalid?: InputProps;
  /**
   * Referenced component InputProps
   */
  invalidMessage?: InputProps;
  /**
   * Referenced component InputProps
   */
  hint?: InputProps;
  className?: Class;
  component?: KsComponentAttribute;
}
