/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `yarn run schema` to regenerate this file.
 */

import type { InputProps } from '@kickstartds/form/lib/input/typing';

/**
 * Additional css classes attached to the textarea element
 */
export type Class = string;
/**
 * Optional custom component identifier
 */
export type KsComponentAttribute = string;

/**
 * Multiline text input, useful for cases where users have a sizable amount of text to enter.
 */
export interface TextAreaProps {
  /**
   * Referenced component InputProps
   */
  label?: InputProps;
  /**
   * Referenced component InputProps
   */
  value?: InputProps;
  /**
   * Referenced component InputProps
   */
  name?: InputProps;
  /**
   * Referenced component InputProps
   */
  disabled?: InputProps;
  /**
   * Referenced component InputProps
   */
  placeholder?: InputProps;
  /**
   * Referenced component InputProps
   */
  hideLabel?: InputProps;
  /**
   * Referenced component InputProps
   */
  icon?: InputProps;
  /**
   * Referenced component InputProps
   */
  invalid?: InputProps;
  /**
   * Referenced component InputProps
   */
  invalidMessage?: InputProps;
  /**
   * Referenced component InputProps
   */
  hint?: InputProps;
  className?: Class;
  component?: KsComponentAttribute;
}
