/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `yarn run schema` to regenerate this file.
 */

/**
 * A short title of the banner
 */
export type Title = string;
/**
 * The main message delivered by the banner
 */
export type Message = string;
/**
 * Choose a size to scale the banner up or down
 */
export type Size = 's' | 'm' | 'l';
/**
 * Set the color contrast of the banner
 */
export type Contrast = 'low' | 'high';
/**
 * Choose the type of information being displayed in the banner
 */
export type Type = 'plain' | 'info' | 'warning' | 'succes' | 'error';
/**
 * Add additional css classes that should be applied to the label
 */
export type AdditionalClasses = string;
/**
 * Optional custom component identifier
 */
export type KsComponentAttribute = string;

/**
 * Component to render a pill / tag / label
 */
export interface BannerProps {
  title?: Title;
  message: Message;
  size?: Size;
  contrast?: Contrast;
  type?: Type;
  className?: AdditionalClasses;
  component?: KsComponentAttribute;
}
